dist: trusty
sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "10"
  - "8"
  - "6"
cache:
  directories:
    - node_modules
script:
  - "npm run lint"
jobs:
   include:
     - stage: npm release
       node_js: "8"
       script: skip
       after_success:
         - npx semantic-release
branches:
  only:
    - master
