version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

executors:
  docker-node:
    parameters:
      version:
        default: 'lts'
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>

commands:
  install:
    steps:
      - run:
          name: Install
          command: npm install

  test:
    steps:
      - run:
          name: Test
          command: npm test

  release:
    steps:
      - run:
          name: Release
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            npx semantic-release@25.0.3

  lint:
    steps:
      - run:
          name: Lint
          command: npm run lint

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    resource_class: small
    parameters:
      version:
        default: 'lts'
        type: string
    executor:
      name: docker-node
      version: <<parameters.version>>
    steps:
      - checkout
      - install
      - test

  lint:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - lint

  release:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - release

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-sca
          filters:
            branches:
              ignore:
                - master
      - security-scans:
          name: Security Scans
          context: open_source-managed
      - lint:
          name: Lint
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - Lint
            - Scan repository for secrets
            - Security Scans
          matrix:
            parameters:
              version:
                - 6.17.1
                - 8.17.0
                - 10.24.1
                - 12.22.12
                - 14.21.3
                - 16.20.2
                - 18.20.8
                - 20.20.2
                - 22.23.1
                - 24.18.0
      - release:
          context:
            - nodejs-install
            - github-release
          requires:
            - test
          filters:
            branches:
              only:
                - master
