version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-sca
          filters:
            branches:
              ignore:
                - master
      - security-scans:
          name: Security Scans
          context: open_source-managed
